# Generated by Django 3.0 on 2020-01-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='textbookmodel',
            name='comment',
        ),
    ]
