# Generated by Django 3.0 on 2020-01-30 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0004_auto_20200130_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='comment',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='receiver',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='is_publick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='textapp.Textbookmodel'),
            preserve_default=False,
        ),
    ]
