# Generated by Django 3.0 on 2020-01-31 05:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0006_auto_20200131_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textbookmodel',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='textbookmodel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
