# Generated by Django 3.0 on 2020-01-31 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0007_auto_20200131_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='is_publick',
        ),
    ]
