# Generated by Django 3.0 on 2020-02-01 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('textapp', '0008_remove_commentmodel_is_publick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='nickname',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='college',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
