# Generated by Django 3.0 on 2020-02-02 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0013_auto_20200203_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroommodel',
            name='target',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatroomlist', to='textapp.Textbookmodel'),
        ),
    ]
