# Generated by Django 3.0 on 2020-02-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0014_auto_20200203_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookmodel',
            name='collegecategory',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='textbookmodel',
            name='facultycategory',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='textbookmodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textbookmodel',
            name='status',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
