# Generated by Django 3.0 on 2020-02-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0015_auto_20200203_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookmodel',
            name='trading',
            field=models.BooleanField(default=False),
        ),
    ]
