# Generated by Django 3.0 on 2020-02-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0016_textbookmodel_trading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbookmodel',
            name='images',
            field=models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to=''),
        ),
    ]
